### ISSUE TITLE
Default keyboard shortcuts sometimes inserting characters into file

### ISSUE THREAD

**Issue by Soleone** [hmatsuda/rails-transporter#78]
### Problem

The default keyboard shortcuts are two-step, to e.g. switch from model to test you first press `ctrl-r` and then `t`. Now if the file does not exist a modal pops up asking if you want to create it. It then switches you to the newly created test file.

But in the model file it inserted the character `t` into your current cursor position. This is sometimes hard to catch and causes syntax errors

### Suggestion

Either make sure extra characters don't get inserted or move to different keybindings that are not two-step, e.g. `ctrl-option-t` or similar.

**Comment by art-solopov** [comment]
+1. This issue actually manifests when any creation modal pops up.

**Comment by hmatsuda** [comment]
Oops. I didn't know this bug because installing vim-mode, this doesn't happen.  Thanks for reporting @Soleone.

**Comment by bronson** [comment]
I'm surprised you use vim-mode @hmatsuda ...  The ctrl-r mapping drives me nuts because now Redo takes 1/2 second to take effect.  And I hit `u` and `ctrl-r` and awful lot.  :)

@Soleone, not sure I agree with trying to map 12 single-step keystrokes.  That sounds hard to remember, assuming you can even find 12 keystrokes free!

Personally, I've disabled the default mappings and added commands so I can just use the command palette.  "Con" completes to "Controller" which fires off `rails-transporter:open-controller`.  (I've only just done this, we'll see if I still like it in a week...)

**Comment by hmatsuda** [comment]
@bronson Thanks for good advice! I don't know Redo task because I'm not awfully familiar with vim. Anyway, I fixed this problem by to show modal dialog instead of atom default system dialog.

Thanks!

**Comment by bronson** [comment]
vim-mode's Redo (`ctrl-r`) is just the opposite of Undo (`u`).

Normally `ctrl-r` responds instantly.  However, when rails-transporter is installed, hitting `ctrl-r` waits around 1/2 second before doing anything to see if I'm going to press a rails-transporter key.  Surprised you haven't noticed this.  Maybe you don't make as many mistakes as I do.  :)

As I said above, I fixed it by disabling rails-transporter's keymap and invoking it from the command palette.  It's great!
